(cl:defpackage easy_handeye-srv
  (:use )
  (:export
   "COMPUTECALIBRATION"
   "<COMPUTECALIBRATION-REQUEST>"
   "COMPUTECALIBRATION-REQUEST"
   "<COMPUTECALIBRATION-RESPONSE>"
   "COMPUTECALIBRATION-RESPONSE"
   "REMOVESAMPLE"
   "<REMOVESAMPLE-REQUEST>"
   "REMOVESAMPLE-REQUEST"
   "<REMOVESAMPLE-RESPONSE>"
   "REMOVESAMPLE-RESPONSE"
   "TAKESAMPLE"
   "<TAKESAMPLE-REQUEST>"
   "TAKESAMPLE-REQUEST"
   "<TAKESAMPLE-RESPONSE>"
   "TAKESAMPLE-RESPONSE"
  ))

