// Generated by gencpp from file easy_handeye/RemoveSample.msg
// DO NOT EDIT!


#ifndef EASY_HANDEYE_MESSAGE_REMOVESAMPLE_H
#define EASY_HANDEYE_MESSAGE_REMOVESAMPLE_H

#include <ros/service_traits.h>


#include <easy_handeye/RemoveSampleRequest.h>
#include <easy_handeye/RemoveSampleResponse.h>


namespace easy_handeye
{

struct RemoveSample
{

typedef RemoveSampleRequest Request;
typedef RemoveSampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveSample
} // namespace easy_handeye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::easy_handeye::RemoveSample > {
  static const char* value()
  {
    return "f2b56f3f27d9d8404f22e6fe88f38b19";
  }

  static const char* value(const ::easy_handeye::RemoveSample&) { return value(); }
};

template<>
struct DataType< ::easy_handeye::RemoveSample > {
  static const char* value()
  {
    return "easy_handeye/RemoveSample";
  }

  static const char* value(const ::easy_handeye::RemoveSample&) { return value(); }
};


// service_traits::MD5Sum< ::easy_handeye::RemoveSampleRequest> should match 
// service_traits::MD5Sum< ::easy_handeye::RemoveSample > 
template<>
struct MD5Sum< ::easy_handeye::RemoveSampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye::RemoveSample >::value();
  }
  static const char* value(const ::easy_handeye::RemoveSampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye::RemoveSampleRequest> should match 
// service_traits::DataType< ::easy_handeye::RemoveSample > 
template<>
struct DataType< ::easy_handeye::RemoveSampleRequest>
{
  static const char* value()
  {
    return DataType< ::easy_handeye::RemoveSample >::value();
  }
  static const char* value(const ::easy_handeye::RemoveSampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::easy_handeye::RemoveSampleResponse> should match 
// service_traits::MD5Sum< ::easy_handeye::RemoveSample > 
template<>
struct MD5Sum< ::easy_handeye::RemoveSampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye::RemoveSample >::value();
  }
  static const char* value(const ::easy_handeye::RemoveSampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye::RemoveSampleResponse> should match 
// service_traits::DataType< ::easy_handeye::RemoveSample > 
template<>
struct DataType< ::easy_handeye::RemoveSampleResponse>
{
  static const char* value()
  {
    return DataType< ::easy_handeye::RemoveSample >::value();
  }
  static const char* value(const ::easy_handeye::RemoveSampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EASY_HANDEYE_MESSAGE_REMOVESAMPLE_H
