controller_list:
  - name: ur5_manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: ur5_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
       - robotiq_85_left_knuckle_joint